%%%%% Set up %%%%%

% Set document style and font size
\documentclass[12pt]{article}

% Style file for DFO Technical Reports
\usepackage{Document/TechReport}

%%%%% Variables %%%%%

% New definitions: Title, year, report number, authors
% Protect lower case words (i.e., species names) in \Addlcwords{}
\newcommand{\trTitle}{Everything you need to know about Pacific herring (\textit{Clupea pallasi}) in British Columbia, Canada}
\newcommand{\trYear}{XXXX}
\newcommand{\trReportNum}{YYYY}
% Optional
\newcommand{\trAuthFootA}{\footnote{E-mail: \texttt{First.Aurhor@dfo-mpo.gc.ca} $|$ telephone: (250)~756.ZZZZ}}
\newcommand{\trAuthsLong}{First A. Author,\trAuthFootA{} Second B. Author}
\newcommand{\trAuthsBack}{Author, F.A., and Author, S.B.}

% New definition: Address
\newcommand{\trAddy}{Fisheries and Oceans Canada\\Science Branch, Pacific Region\\Pacific Biological Station\\3190 Hammond Bay Road\\Nanaimo, BC \enskip V9T 6N7}

% Abstract
\newcommand{\trAbstract}{
This is the abstract.}

% Resume (i.e., French abstract)
\newcommand{\trResume}{
Et en français...
}

%%%%% Start %%%%%

% Start the document
\begin{document}

%%%% Front matter %%%%%

% Add the first few pages
\frontmatter

%%%%% Drafts %%%%%

%\linenumbers  % Line numbers
%\onehalfspacing  % Extra space between lines
%\renewcommand{\headrulewidth}{1pt}  % Header line
%\pagestyle{fancy}\fancyhead[c]{Draft: Do not cite or circulate}  % Header text

%%%%% Main document %%%%%

\section{INTRODUCTION}

Introduction text. Input tables, figures, citations, and references as usual.

%%%%% References %%%%%

% Style file
\bibliographystyle{Document/CJFAS}

% References
%\addcontentsline{toc}{section}{\refname}\bibliography{Document/[FileName]}

%%%%% Fin %%%%%

% The end
\end{document}
