%%%%% Set up %%%%%

% Set document style and font size
\documentclass[12pt]{article}

% File path to resources (style file etc)
\newcommand{\locRes}{Document}

% Style file for DFO Technical Reports
\usepackage{\locRes/TechReport}


%%%%% Variables %%%%%

% Fish name
\newcommand{\fishName}{Pacific Herring}
% Science name: use math mode to prevent case changes
\newcommand{\scienceName}{$Clupea$ $pallasii$}

% New definitions: Title, year, report number, authors
% Protect lower case words (i.e., species names) in \Addlcwords{}, in "TechReport.sty", and use math mode.
\newcommand{\trTitle}{Everything you need to know about \fishName{} (\scienceName{}) in British Columbia, Canada}
\newcommand{\trYear}{XXXX}
\newcommand{\trReportNum}{YYYY}
% Optional
\newcommand{\trAuthFootA}{\footnote{E-mail: \texttt{First.Aurhor@dfo-mpo.gc.ca} $|$ telephone: (250)~756.ZZZZ}}
\newcommand{\trAuthsLong}{First A. Author,\trAuthFootA{} Second B. Author}
\newcommand{\trAuthsBack}{Author, F.A., and Author, S.B.}

% New definition: Address
\newcommand{\trAddy}{Fisheries and Oceans Canada\\Science Branch, Pacific Region\\Pacific Biological Station\\3190 Hammond Bay Road\\Nanaimo, BC \enskip V9T 6N7}

% Abstract
\newcommand{\trAbstract}{
This is the abstract.}

% Resume (i.e., French abstract)
\newcommand{\trResume}{
Et en fran?ais...
}

%%%%% Start %%%%%

% Start the document
\begin{document}

%%%% Front matter %%%%%

% Add the first few pages
\frontmatter

%%%%% Drafts %%%%%

%\linenumbers  % Line numbers
%\onehalfspacing  % Extra space between lines
%\renewcommand{\headrulewidth}{1pt}  % Header line
%\pagestyle{fancy}\fancyhead[c]{Draft: Do not cite or circulate}  % Header text

%%%%% Main document %%%%%

\section{INTRODUCTION}

The following sections describe our model of algae egg density (\autoref{secEggDens}, surface spawn (\autoref{secSurface}), Macrocystis spawn (\autoref{secMacro}), and understory spawn (\autoref{secUnder}).

\subsection{ALGAE EGG DENSITY}\label{secEggDens}

\citet{Schweigert2005} developed a predictive model of algae egg density in thousands of eggs per square metre from egg layers, proportion of the quadrat covered by algae, and an algae coefficient using a generalized linear model.
Algae coefficients account for the effect of algae morphology on \fishName{} egg density (\autoref{tabAlgCoefs}).
The model takes the form \citep{Schweigert2005}
\begin{equation}\label{eqEggDensUnderA}
\mli{EggDensAlg}_a = 631.316 \cdot \mli{AlgLyrs}_a^{0.6355} \cdot \mli{AlgProp}_a^{1.4130} \cdot \mli{Coef}_a
\end{equation}
where $\mli{AlgLyrs}_a$ is the number of egg layers on algae $a$,
$\mli{AlgProp}_a$ is the proportion of the quadrat covered by algae $a$,
$\mli{Coef}_a$ is the coefficient for algae $a$, and
$\mli{EggDensAlg}_a$ is in $\text{eggs} \cdot 10^3 \cdot \text{m}^{-2}$.
The total algae egg density for quadrat $q$ is
\begin{equation}
\mli{EggDensAlg}_q = \sum_{a=1}^{A} \mli{EggDensAlg}_a \enspace .
\end{equation}

\begin{table}
\centering
\caption[Algae types and coefficients for \fishName{} understory spawn surveys]
{Algae types, $a$ and coefficients, $\mli{Coef}$ for \fishName{} understory spawn surveys \citep{Schweigert2005}.}
\begin{tabular}{lr}
\toprule
Algae type, $a$ & Coefficient, $\mli{Coef}$ \\
\midrule
Grasses        & 0.9715 \\
Grunge         & 1.0000 \\
Kelp, flat     & 0.9119 \\
Kelp, standing & 1.1766 \\
Leafy algae    & 0.6553 \\
Rockweed       & 0.7793 \\
Sargassum      & 1.1766 \\
Stringy algae  & 1.0000 \\
\bottomrule
\end{tabular}
\label{tabAlgCoefs}
\end{table}

\subsection{SURFACE SPAWN}\label{secSurface}

Surface spawn surveyors use the aforementioned transect interval when possible, but the sampling interval relies on surveyor judgement and available resources.
If the spawn area is sufficiently large, surface surveyors usually sample along permanent transects.
Small spawns can still be mapped as they were historically, with surveyors deciding how to sample the spawn.
To sample, surveyors deploy specialized rakes throughout the spawn to determine vegetation type, number of egg layers (see below), and vegetation coverage.
In shallow waters a viewing box may be employed, and at low tide a portion of the spawn may be visible for direct observation.
In some cases, we adjust spawn width to improve spawn index estimates (\hyperref[secWidthAdjust]{appendix \ref{secWidthAdjust}}).

For eggs on substrate, one egg layer is a layer of eggs one egg thick over the entire spawned surface (\autoref{figLayersSubstrate}).
For eggs on algae, egg layers are counted one of two ways depending on whether the algae is flat or round in cross-section.
Egg layers on flat algae are counted on both sides of the algae (\autoref{figLayersAlgaeFlat}); egg layers on round algae are counted across the diameter of the algae (\autoref{figLayersAlgaeRound}).

\begin{figure}
\centering
\begin{subfigure}[b]{0.3\linewidth}
\includegraphics[width=\linewidth]{Figures/LayersSubstrate.png}
\caption{Substrate with 1.5 egg layers.}
\label{figLayersSubstrate}
\end{subfigure}
\hfill
\begin{subfigure}[b]{0.3\linewidth}
\includegraphics[width=\linewidth]{Figures/LayersAlgaeFlat.png}
\caption{Flat algae with 2.5 egg layers.}
\label{figLayersAlgaeFlat}
\end{subfigure}
\hfill
\begin{subfigure}[b]{0.3\linewidth}
\includegraphics[width=\linewidth]{Figures/LayersAlgaeRound.png}
\caption{Round algae with 2.5 egg layers.}
\label{figLayersAlgaeRound}
\end{subfigure}
\caption[Number of \fishName{} egg layers]
{Cross-sections showing the number of \fishName{} egg layers on substrate, flat algae, and round algae.
Diagrams copied with permission from the \href{http://www.pac.dfo-mpo.gc.ca/science/species-especes/pelagic-pelagique/herring-hareng/hertags/pdf/SurveyManual.pdf}{\color{blue}{\fishName{} spawn survey manual}}.}
\label{figLayers}
\end{figure}

\subsection{MACROCYSTIS SPAWN}\label{secMacro}

Macrocystis spawn surveyors take a census of Macrocystis plants within $1\,\text{m}$ of the transect line, on both the left- and right-hand sides.
We refer to the swath of substrate along Macrocystis transects as the transect swath, $\mli{Swath} = 2\,\text{m}$.
Divers categorize Macrocystis plants as either `mature' or `immature' based on stipe height; mature plants have stipes $\geq1\,\text{m}$ high, and are the only plants used for Macrocystis spawn index calculations.
Immature plants are excluded because \fishName{} spawn on Macrocystis fronds, not stipes; immature plants have limited fronds and slimy stipes that prevent egg adhesion.
In addition, spawn is typically higher up in Macrocystis plants.
For each mature plant, divers record height, number of stalks, and number of egg layers.
For each transect, divers record the average number of egg layers.

\subsection{UNDERSTORY SPAWN}\label{secUnder}

Understory spawn surveyors place quadrats along transects, with a target frequency of $\geq 5$ quadrats per transect, given a minimum spacing of $2\,\text{m}$, and a maximum spacing of $40\,\text{m}$.
Similar to how the first transect is moved in from one end of the spawn, the first quadrat is moved in from the edge of the spawn to the first $5\,\text{m}$ mark on the transect line to avoid surveying areas with patchy and sparse egg layers.
Within each quadrat, divers record the dominant (i.e., most heavily spawned) substrate type, percentage of the quadrat covered by spawn, and number of egg layers.
In addition, divers identify the three most abundant algae types that have spawn.
For each of these algae types, divers record the percentage of the quadrat covered by the algae, and number of egg layers.

%%%%% References %%%%%

% Style file
\bibliographystyle{\locRes/CJFAS}

% References
\addcontentsline{toc}{section}{\refname}\bibliography{Example}

%%%%% Appendices %%%%%

% Begin the appendices
\begin{appendices}

\section{SPAWN WIDTH ADJUSTMENTS}\label{secWidthAdjust}

Spawn width is a critical component of spawn index calculations.
There are two cases where we adjust spawn width estimates to improve spawn index estimates: surface surveys in all years from 1951 to present, and dive surveys between 2003 and 2013.

% End appendices
\end{appendices}

%%%%% Fin %%%%%

% The end
\end{document}
